### PR TITLE
setuptools requirement

### PR DESCRIPTION
**Pull request by burnout87**

### CODE REVIEW

**Comment by burnout87** [comment]
`setuptools` is not included in python 3.13 (tested locally, compared with previous python versions).

So by limiting the python version up to 3.12, the error disappears.

**Comment by volodymyrss** [comment]
> `setuptools` is not included in python 3.13 (tested locally, compared with previous python versions).
> 
> So by limiting the python version up to 3.12, the error disappears.
> 
> What do you think @volodymyrss ?

Sounds good!

And please make an to change oda-api to avoid using setuptools, to make compatible with python 3.13 eventually.

**Comment by burnout87** [comment]
To mention that also by adding `setuptools` as a requirement within the conda recipe, in the `meta.yaml` file, did not solve the issue

**Comment by volodymyrss** [comment]
https://github.com/oda-hub/oda_api/issues/285

**Pull request merged**
